services:
  twitch-points-bot:
    image: rdavidoff/twitch-channel-points-miner-v2:latest
    container_name: twitch-points-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount to correct path that Docker image expects
      - ./logs:/usr/src/app/logs
      - ./run.py:/usr/src/app/run.py
    environment:
      - TZ=UTC
